import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/sidebar";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { ThemeProvider } from "@/components/shared/theme-provider";
import { ContextProvider } from "@/app/provider/global-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${montserrat.className} antialiased grid ${
            userId && "grid-cols-[300px_1fr]"
          } grid-rows-1 p-4 gap-x-8`}
        >
          <ContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {userId && <Sidebar />}
              <ScrollArea className="rounded-md overflow-auto pr-4 max-h-full">
                {children}
                <ScrollBar orientation="horizontal" />
              </ScrollArea>
            </ThemeProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
